from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

from src.custom_exception import CustomException
from src.logger import get_logger

logger = get_logger(__name__)


async def get_recomendations_from_llm(user_prompt: str, tags_json: str, model: str, api_key: str) -> dict:
    try:
        logger.info("##### INITIALIZING RECOMMEND_FROM_LLM.py ##### ")

        try:
                logger.info("##### Creating RAG chain #####")
                prompt = """
                        You are a cultural strategist who advises writers, content creators, and producers.

                        The user has provided a creative goal or question. You also have audience insights generated by Qloo, including tags with high cultural affinity.

                        Your task is to:
                        1. Analyze the user's creative objective and interpret their intent.
                        2. Combine it with the cultural tags to infer traits and preferences of the target audience.
                        3. Generate creative recommendations for tone, style, format, themes, or storytelling elements.
                        4. Optionally suggest content inspirations or successful examples that match this profile.

                        Use clear, human-friendly language, and structure your output in markdown.

                        ---

                        ### User's Creative Goal:
                        "{user_prompt}"

                        ---

                        ### Cultural Tags (from Qloo):
                        {tags_json}
                        """
                llm = ChatOpenAI(
                    base_url="https://openrouter.ai/api/v1",
                    openai_api_key=api_key,
                    model=model
                )
                prompt_template = ChatPromptTemplate.from_template(prompt)
                logger.info("##### FINISHED - Creating RAG chain #####")
        except Exception as e:
                logger.error(f"Error while Creating RAG chain: {e}")
                raise CustomException("Error while Creating RAG chain", e)
        try:
                logger.info("##### GETTING THE ANSWER FROM CHAIN #####")
                answer = prompt_template | llm | StrOutputParser()
                final_answer = answer.invoke({"user_prompt": user_prompt,"tags_json": tags_json})
                logger.info("##### FINISHED - GETTING THE ANSWER FROM CHAIN #####")
        except Exception as e:
                logger.error(f"Error while GETTING THE ANSWER FROM CHAIN: {e}")
                raise CustomException("Error GETTING THE ANSWER FROM CHAIN", e)
        
        logger.info("##### FINISHED -- RECOMMEND_FROM_LLM.py ##### ")
        return final_answer
    except Exception as e:
        logger.error(f"ERROR INITIALIZING RECOMMEND_FROM_LLM.py: {e}")
        raise CustomException("ERROR INITIALIZING RECOMMEND_FROM_LLM.py", e)
